@extends('layouts.shop')

@section('title', $content['title'] . ' | Marche Peyi')
@section('description', $content['intro'])

@section('content')
    <section class="soft-grid px-4 py-14 dark:bg-ink sm:px-8 lg:py-20"><div class="mx-auto max-w-5xl"><p class="section-kicker">{{ $content['eyebrow'] }}</p><h1 class="brand-display mt-4 text-5xl uppercase text-forest dark:text-meadow sm:text-7xl">{{ $content['title'] }}</h1><p class="mt-6 max-w-3xl text-base font-semibold leading-8 text-cocoa/70 dark:text-cream/70">{{ $content['intro'] }}</p></div></section>
    <section class="bg-cream px-4 py-14 dark:bg-ink sm:px-8 lg:py-16"><div class="mx-auto grid max-w-5xl gap-5">@foreach ($content['sections'] as $section)<article class="utility-section bg-linen dark:bg-white/5"><p class="section-kicker">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</p><h2 class="mt-3 text-2xl font-black text-forest dark:text-meadow">{{ $section['title'] }}</h2><p class="mt-3 text-sm leading-7 text-cocoa/70 dark:text-cream/70">{{ $section['body'] }}</p></article>@endforeach</div></section>
    <section class="bg-linen px-4 py-14 dark:bg-[#163319] sm:px-8 lg:py-16"><div class="utility-section mx-auto grid max-w-5xl gap-6 lg:grid-cols-[0.85fr_1.15fr]"><div><p class="section-kicker">{{ __('home.contact.eyebrow') }}</p><h2 class="mt-3 text-3xl font-black text-forest dark:text-meadow">{{ __('home.contact.title') }}</h2><p class="mt-3 text-sm leading-7 text-cocoa/65 dark:text-cream/65">{{ __('home.footer.line') }}</p></div><div class="grid gap-4 sm:grid-cols-2"><div class="rounded-[1.25rem] bg-linen p-5 dark:bg-white/5"><p class="text-xs font-black uppercase tracking-[0.18em] text-forest dark:text-meadow">{{ __('home.contact.company') }}</p><p class="mt-2 text-sm font-semibold text-cocoa dark:text-cream">{{ __('home.contact.address') }}</p></div><div class="rounded-[1.25rem] bg-linen p-5 dark:bg-white/5"><p class="text-xs font-black uppercase tracking-[0.18em] text-forest dark:text-meadow">Contact</p><p class="mt-2 text-sm font-semibold text-cocoa dark:text-cream">{{ __('home.contact.phone') }}</p><p class="mt-1 text-sm text-cocoa/65 dark:text-cream/65">{{ __('home.contact.email') }}</p></div></div></div></section>
@endsection
