<dialog id="product-create-wizard" class="admin-dialog admin-dialog-wide" @if(session('admin_modal') === 'product-create') data-open-on-load @endif>
    <form
        method="POST"
        action="{{ route('admin.catalog.products.store', ['locale' => $locale]) }}"
        enctype="multipart/form-data"
        class="admin-modal-card"
        x-data="{
            step: 1,
            previews: [],
            primary: Number(@js((int) old('primary_image_index', 0))),
            iconPreview: null,
            selectImages(event) {
                this.previews.forEach(item => URL.revokeObjectURL(item.url));
                this.previews = Array.from(event.target.files).map((file, index) => ({ name: file.name, url: URL.createObjectURL(file), index }));
                if (this.primary >= this.previews.length) this.primary = 0;
            },
            selectIcon(event) {
                if (this.iconPreview) URL.revokeObjectURL(this.iconPreview);
                this.iconPreview = event.target.files[0] ? URL.createObjectURL(event.target.files[0]) : null;
            },
            next() {
                const invalid = this.$root.querySelector(`[data-product-step='${this.step}'] :invalid`);
                if (invalid) { invalid.reportValidity(); return; }
                this.step = Math.min(4, this.step + 1);
            }
        }"
    >
        @csrf
        <input type="hidden" name="primary_image_index" x-model="primary">

        <header class="flex items-start justify-between border-b border-leaf/10 p-5 dark:border-white/10 sm:p-6">
            <div>
                <p class="admin-kicker">{{ $isEnglish ? 'Complete product file' : 'Fiche produit complète' }}</p>
                <h2 class="mt-2 text-2xl font-black">{{ $isEnglish ? 'Add a product' : 'Ajouter un produit' }}</h2>
                <p class="mt-2 text-sm admin-muted">{{ $isEnglish ? 'Identity, prices, content and media.' : 'Identité, prix, contenu et médias.' }}</p>
            </div>
            <button type="button" data-dialog-close class="admin-icon-btn" aria-label="{{ $isEnglish ? 'Close' : 'Fermer' }}"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6 6 18M6 6l12 12"/></svg></button>
        </header>

        <div class="grid grid-cols-4 border-b border-leaf/10 dark:border-white/10">
            @foreach ([1 => $isEnglish ? 'Identity' : 'Identité', 2 => $isEnglish ? 'Prices' : 'Prix et stock', 3 => $isEnglish ? 'Content' : 'Contenu', 4 => $isEnglish ? 'Media' : 'Médias'] as $number => $label)
                <button type="button" class="border-b-2 px-1 py-3 text-[11px] font-black transition sm:text-sm" :class="step === {{ $number }} ? 'border-orange-500 text-orange-600' : 'border-transparent text-cocoa/45 dark:text-cream/45'" x-on:click="if ({{ $number }} < step) step = {{ $number }}">
                    <span class="mx-auto mb-1 grid h-7 w-7 place-items-center rounded-full" :class="step >= {{ $number }} ? 'bg-orange-500 text-white' : 'bg-cocoa/10 dark:bg-white/10'">{{ $number }}</span>{{ $label }}
                </button>
            @endforeach
        </div>

        <div class="p-5 sm:p-6">
            @if(session('admin_modal') === 'product-create' && $errors->any())
                <div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{{ $errors->first() }}</div>
            @endif

            <section x-show="step === 1" data-product-step="1" class="grid gap-4 sm:grid-cols-2">
                <div class="sm:col-span-2"><p class="admin-kicker">{{ $isEnglish ? 'Step 1' : 'Étape 1' }}</p><h3 class="mt-1 text-xl font-black">{{ $isEnglish ? 'Product identity' : 'Identité du produit' }}</h3></div>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'French name' : 'Nom français' }} {{ $isEnglish ? '' : '*' }}</span><input name="name_fr" value="{{ old('name_fr') }}" class="admin-input" @if(! $isEnglish) required @endif></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'English name' : 'Nom anglais' }} {{ $isEnglish ? '*' : '' }}</span><input name="name_en" value="{{ old('name_en') }}" class="admin-input" @if($isEnglish) required @endif></label>
                <label><span class="admin-kicker mb-2 block">Slug <small class="normal-case tracking-normal admin-muted">({{ $isEnglish ? 'automatic' : 'automatique' }})</small></span><input name="slug" value="{{ old('slug') }}" class="admin-input" placeholder="{{ $isEnglish ? 'Generated from the name' : 'Généré depuis le nom' }}"></label>
                <label><span class="admin-kicker mb-2 block">SKU <small class="normal-case tracking-normal admin-muted">({{ $isEnglish ? 'automatic' : 'automatique' }})</small></span><input name="sku" value="{{ old('sku') }}" class="admin-input" placeholder="{{ $isEnglish ? 'Generated by the backend' : 'Généré par le backend' }}"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Category' : 'Catégorie' }}</span><select name="category_id" class="admin-select"><option value="">{{ $isEnglish ? 'Uncategorized (automatic)' : 'Non classé (automatique)' }}</option>@foreach ($categoryRows as $category) @php $categoryName = data_get($category, "name.{$locale}") ?: data_get($category, 'name.fr') ?: ($category['slug'] ?? 'Catégorie'); @endphp<option value="{{ $category['id'] }}" @selected((string) old('category_id') === (string) $category['id'])>{{ $categoryName }}</option>@endforeach</select></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Barcode / EAN' : 'Code-barres / EAN' }}</span><input name="barcode" value="{{ old('barcode') }}" class="admin-input" inputmode="numeric"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Brand' : 'Marque' }}</span><input name="brand" value="{{ old('brand') }}" class="admin-input"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Supplier reference' : 'Référence fournisseur' }}</span><input name="supplier_reference" value="{{ old('supplier_reference') }}" class="admin-input"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'French origin' : 'Origine FR' }}</span><input name="origin_fr" value="{{ old('origin_fr') }}" class="admin-input"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'English origin' : 'Origine EN' }}</span><input name="origin_en" value="{{ old('origin_en') }}" class="admin-input"></label>
            </section>

            <section x-show="step === 2" x-cloak data-product-step="2" class="grid gap-4 sm:grid-cols-2">
                <div class="sm:col-span-2"><p class="admin-kicker">{{ $isEnglish ? 'Step 2' : 'Étape 2' }}</p><h3 class="mt-1 text-xl font-black">{{ $isEnglish ? 'Prices, VAT and inventory' : 'Prix, TVA et stock' }}</h3><p class="mt-2 text-sm admin-muted">{{ $isEnglish ? 'The sale price is entered with VAT included.' : 'Le prix de vente est saisi toutes taxes comprises.' }}</p></div>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Purchase price (€)' : 'Prix d’achat (€)' }}</span><input name="purchase_price_eur" value="{{ old('purchase_price_eur') }}" type="number" min="0" step="0.01" class="admin-input"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Sale price incl. VAT (€)' : 'Prix de vente TTC (€)' }} *</span><input name="sale_price_ttc_eur" value="{{ old('sale_price_ttc_eur') }}" type="number" min="0.01" step="0.01" class="admin-input" required></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Compare-at price (€)' : 'Prix barré TTC (€)' }}</span><input name="compare_at_price_eur" value="{{ old('compare_at_price_eur') }}" type="number" min="0.01" step="0.01" class="admin-input"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'VAT class' : 'Classe TVA' }} *</span><select name="tax_class" class="admin-select" required><option value="food" @selected(old('tax_class', 'food') === 'food')>{{ $isEnglish ? 'Food — reduced rate' : 'Alimentaire — taux réduit' }}</option><option value="standard" @selected(old('tax_class') === 'standard')>{{ $isEnglish ? 'Standard rate' : 'Taux standard' }}</option></select></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Available stock' : 'Stock disponible' }} *</span><input name="stock_quantity" value="{{ old('stock_quantity', 0) }}" type="number" min="0" class="admin-input" required></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Maximum per order' : 'Maximum par commande' }}</span><input name="max_order_quantity" value="{{ old('max_order_quantity') }}" type="number" min="1" class="admin-input"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Weight (grams)' : 'Poids (grammes)' }}</span><input name="weight_grams" value="{{ old('weight_grams') }}" type="number" min="1" class="admin-input"></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Sales unit' : 'Unité de vente' }}</span><input name="unit_label" value="{{ old('unit_label') }}" class="admin-input" placeholder="{{ $isEnglish ? 'unit, kg, box…' : 'pièce, kg, boîte…' }}"></label>
            </section>

            <section x-show="step === 3" x-cloak data-product-step="3" class="grid gap-4 sm:grid-cols-2">
                <div class="sm:col-span-2"><p class="admin-kicker">{{ $isEnglish ? 'Step 3' : 'Étape 3' }}</p><h3 class="mt-1 text-xl font-black">{{ $isEnglish ? 'Bilingual sales content' : 'Contenu commercial bilingue' }}</h3></div>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Short description FR' : 'Description courte FR' }}</span><textarea name="short_description_fr" class="admin-textarea min-h-24">{{ old('short_description_fr') }}</textarea></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Short description EN' : 'Description courte EN' }}</span><textarea name="short_description_en" class="admin-textarea min-h-24">{{ old('short_description_en') }}</textarea></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Full description FR' : 'Description complète FR' }}</span><textarea name="description_fr" class="admin-textarea min-h-40">{{ old('description_fr') }}</textarea></label>
                <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Full description EN' : 'Description complète EN' }}</span><textarea name="description_en" class="admin-textarea min-h-40">{{ old('description_en') }}</textarea></label>
            </section>

            <section x-show="step === 4" x-cloak data-product-step="4" class="space-y-5">
                <div><p class="admin-kicker">{{ $isEnglish ? 'Step 4' : 'Étape 4' }}</p><h3 class="mt-1 text-xl font-black">{{ $isEnglish ? 'Images and publication' : 'Images et publication' }}</h3><p class="mt-2 text-sm admin-muted">{{ $isEnglish ? 'JPG, PNG or WebP. Up to 12 images, 5 MB each.' : 'JPG, PNG ou WebP. Jusqu’à 12 images de 5 Mo chacune.' }}</p></div>
                <label class="block rounded-2xl border-2 border-dashed border-orange-300 bg-orange-50/60 p-6 text-center transition hover:bg-orange-50 dark:border-orange-500/40 dark:bg-orange-500/5">
                    <svg class="mx-auto h-9 w-9 text-orange-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 16l4-4 4 4 3-3 5 5"/><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/></svg>
                    <span class="mt-3 block font-black">{{ $isEnglish ? 'Choose product images *' : 'Choisir les images du produit *' }}</span>
                    <input class="sr-only" type="file" name="product_images[]" accept="image/jpeg,image/png,image/webp" multiple required x-on:change="selectImages($event)">
                </label>
                <div x-show="previews.length" class="grid grid-cols-2 gap-3 sm:grid-cols-4">
                    <template x-for="item in previews" :key="item.url">
                        <button type="button" class="relative overflow-hidden rounded-xl border-2 bg-white p-1" :class="primary === item.index ? 'border-orange-500' : 'border-transparent'" x-on:click="primary = item.index">
                            <img :src="item.url" :alt="item.name" class="aspect-square w-full rounded-lg object-cover">
                            <span class="absolute bottom-2 left-2 rounded-full px-2 py-1 text-[10px] font-black" :class="primary === item.index ? 'bg-orange-500 text-white' : 'bg-black/65 text-white'" x-text="primary === item.index ? @js($isEnglish ? 'PRIMARY' : 'PRINCIPALE') : @js($isEnglish ? 'Set primary' : 'Définir')"></span>
                        </button>
                    </template>
                </div>
                <div class="grid gap-4 sm:grid-cols-2">
                    <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Image alt text FR' : 'Texte alternatif FR' }}</span><input name="image_alt_fr" value="{{ old('image_alt_fr') }}" class="admin-input"></label>
                    <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Image alt text EN' : 'Texte alternatif EN' }}</span><input name="image_alt_en" value="{{ old('image_alt_en') }}" class="admin-input"></label>
                </div>
                <div class="grid gap-4 rounded-2xl border border-leaf/10 p-4 dark:border-white/10 sm:grid-cols-[120px_1fr] sm:items-center">
                    <div class="grid aspect-square place-items-center overflow-hidden rounded-2xl bg-cocoa/5 dark:bg-white/5"><img x-show="iconPreview" :src="iconPreview" class="h-full w-full object-cover"><svg x-show="!iconPreview" class="h-9 w-9 text-cocoa/30 dark:text-cream/30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="4"/><path d="M8 12h8M12 8v8"/></svg></div>
                    <label><span class="admin-kicker mb-2 block">{{ $isEnglish ? 'Product icon' : 'Icône du produit' }}</span><input type="file" name="product_icon" accept="image/jpeg,image/png,image/webp" class="block w-full text-sm" x-on:change="selectIcon($event)"><small class="mt-2 block admin-muted">{{ $isEnglish ? 'Square image recommended, maximum 2 MB.' : 'Image carrée recommandée, maximum 2 Mo.' }}</small></label>
                </div>
                <label class="flex items-center gap-3 rounded-xl bg-cocoa/5 p-4 dark:bg-white/5"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((string) old('is_active', '1') === '1') class="h-5 w-5 rounded border-leaf/20 text-orange-600 focus:ring-orange-500"><span class="text-sm font-bold">{{ $isEnglish ? 'Publish immediately after creation' : 'Publier immédiatement après la création' }}</span></label>
            </section>
        </div>

        <footer class="flex items-center justify-between gap-3 border-t border-leaf/10 p-5 dark:border-white/10 sm:p-6">
            <button type="button" class="admin-btn-secondary" x-show="step > 1" x-on:click="step--">{{ $isEnglish ? 'Previous' : 'Précédent' }}</button>
            <button type="button" data-dialog-close class="admin-btn-secondary" x-show="step === 1">{{ $isEnglish ? 'Cancel' : 'Annuler' }}</button>
            <div class="ml-auto">
                <button type="button" class="admin-btn" x-show="step < 4" x-on:click="next()">{{ $isEnglish ? 'Next' : 'Suivant' }} →</button>
                <button type="submit" class="admin-btn" x-show="step === 4">{{ $isEnglish ? 'Create product' : 'Créer le produit' }}</button>
            </div>
        </footer>
    </form>
</dialog>
